services:
  dinov3_ros:
    image: dinov3_ros:trt
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile_local to copy from local
      network: host # This prevents freezing in commands that require DNS resolution, such as apt-get update
    container_name: dinov3_ros
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/dinov3_ros # Add this to allow any change in the host and reflect it in the container
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      #- RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
      - /dev/video0:/dev/video0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    #restart: always
    command: sleep infinity
