dinov3_node:
  ros__parameters:
    # General params for image
    img_size: 640
    patch_size: 16
    img_mean: [0.485, 0.456, 0.406]
    img_std: [0.229, 0.224, 0.225]
    device: 'cuda'

    # Params for dino model
    dino_model:
      repo_path : '/dinov3_ros/dinov3'
      model_name: 'dinov3_vits16plus'
      weights_path: '/dinov3_ros/dinov3_toolkit/backbone/weights/dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth'
      n_layers: 12
      embed_dim: 384
      source: "local"

    # Params for object detection (od)
    detection_model:
      weights_path: '/dinov3_ros/dinov3_toolkit/head_detection/weights/model.pth'
      classes_path: '/dinov3_ros/dinov3_toolkit/head_detection/class_names.txt'
      fpn_ch: 192
      n_convs: 4
      score_thresh: 0.2
      nms_thresh: 0.1

    # Params for semantic segmentation (sseg)
    segmentation_model:
      weights_path: '/dinov3_ros/dinov3_toolkit/head_segmentation/weights/model.pth'
      classes_path: '/dinov3_ros/dinov3_toolkit/head_segmentation/class_names.txt'
      hidden_dim: 256
      target_size: 320

    # Params for depth estimation
    depth_model:
      weights_path: '/dinov3_ros/dinov3_toolkit/head_depth/weights/model.pth'

    # Params for optical flow model
    optical_flow_model:
      weights_path: '/dinov3_ros/dinov3_toolkit/head_optical_flow/weights/model.pth'
      proj_channels: 256
      radius: 4
      fusion_channels: 320
      fusion_layers: 3
      convex_up: 16
      refinement_layers: 2