dinov3_node:
  ros__parameters:
    # General params for image
    img_size: 640
    img_mean: [0.485, 0.456, 0.406]
    img_std: [0.229, 0.224, 0.225]

    # Params for dino model
    dino_model:
      onnx_path: '/dinov3_ros/dinov3_toolkit/backbone/weights/dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.onnx' # For TensorRT

    # Params for object detection (od)
    detection_model:
      onnx_path: '/dinov3_ros/dinov3_toolkit/head_detection/weights/model.onnx' # For TensorRT
      classes_path: '/dinov3_ros/dinov3_toolkit/head_detection/class_names.txt'
      score_thresh: 0.2
      nms_thresh: 0.1

    # Params for semantic segmentation (sseg)
    segmentation_model:
      onnx_path: '/dinov3_ros/dinov3_toolkit/head_segmentation/weights/model.onnx' # For TensorRT
      classes_path: '/dinov3_ros/dinov3_toolkit/head_segmentation/class_names.txt'

    # Params for depth estimation
    depth_model:
      onnx_path: '/dinov3_ros/dinov3_toolkit/head_depth/weights/model.onnx' # For TensorRT

    # Params for optical flow model
    optical_flow_model:
      onnx_path: '/dinov3_ros/dinov3_toolkit/head_optical_flow/weights/model.onnx' # For TensorRT

    # Params for TensorRT variables
    tensorrt_params:
      precision: 'float16'
      device_index: 0
      dla_core: -1
